version: "3"

services:

  redis-cluster:
    image: grokzen/redis-cluster
    environment: 
      IP: ${REDIS_CLUSTER_IP}
      SENTINEL: ${REDIS_USE_SENTINEL}
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'

volumes:
  db_data:  
    driver: local

