version: "3"

services:
  short_db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
      - ./mariadb.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - 3307:3306
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  sysbench-ps:
    image: perconalab/sysbench
    depends_on:
      - short_db
    command: >
        bash -c "
            set -o xtrace
            sleep 20
            mysql \
                --host=short_db \
                --port=3307 \
                --user=root \
                --password=${DB_PASSWORD} \
                -e 'CREATE DATABASE IF NOT EXISTS sbtest'
            sysbench \
                --db-driver=mysql \
                --mysql-host=short_db \
                --mysql-port=3306 \
                --mysql-user=root \
                --mysql-password=${DB_PASSWORD} \
                --mysql-db=sbtest \
                --mysql-table-engine=innodb \
                --oltp-table-size=1000000 \
                /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua \
                prepare
            sysbench \
                --rate=200 \
                --threads=64 \
                --report-interval=10 \
                --time=0 \
                --events=0 \
                --rand-type=pareto \
                --db-driver=mysql \
                --mysql-host=short_db \
                --mysql-port=3307 \
                --mysql-user=root \
                --mysql-password=${DB_PASSWORD} \
                --mysql-db=sbtest \
                --mysql-table-engine=innodb \
                --oltp-reconnect \
                --oltp-table-size=1000000 \
                /usr/share/sysbench/tests/include/oltp_legacy/select.lua \
                run
        "

volumes:
  db_data:
    driver: local