version: "3"

services:
  short_db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  short_api:
    build: .
    restart: always
    depends_on:
      - short_db
    volumes:
      - ./:/usr/app
    ports:
      - ${PORT}:8080
    links:
      - short_db
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_HOST: short_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      SHORT_PREFIX_KEY: ${SHORT_PREFIX_KEY}

volumes:
  db_data:
    driver: local