version: "3"

services:
  short_db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
      - ./mariadb.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: "project"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3307:3306
    ulimits:
      nofile:
        soft: "66666"
        hard: "66666"

  short_redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

#  redis-node-0:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-0:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-node-1:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-1:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-node-2:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-2:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-node-3:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-3:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-node-4:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-4:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-node-5:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    volumes:
#      - redis-cluster_data-5:/bitnami/redis/data
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#
#  redis-cluster-init:
#    image: docker.io/bitnami/redis-cluster:6.2-debian-10
#    depends_on:
#      - redis-node-0
#      - redis-node-1
#      - redis-node-2
#      - redis-node-3
#      - redis-node-4
#      - redis-node-5
#    environment:
#      ALLOW_EMPTY_PASSWORD: "YES"
#      REDIS_NODES: "redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5"
#      REDIS_CLUSTER_REPLICAS: 1
#      REDIS_CLUSTER_CREATOR: "yes"

volumes:
  db_data:
    driver: local
#  redis-cluster_data-0:
#    driver: local
#  redis-cluster_data-1:
#    driver: local
#  redis-cluster_data-2:
#    driver: local
#  redis-cluster_data-3:
#    driver: local
#  redis-cluster_data-4:
#    driver: local
#  redis-cluster_data-5:
#    driver: local
