version: "3"

services:
  short_db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
      - ./mariadb.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - 3307:3306
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

volumes:
  db_data:
    driver: local