version: "3"

services:
  short_db:
    image: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
      - ./mariadb.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports: 
      - 3307:3306
    ulimits:
      nofile:
        soft: "66666"
        hard: "66666"

  short_redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6666:6379

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
